### ISSUE TITLE
Remeshing fails when an all the vertices of an element belong to faces with the same tag

### ISSUE THREAD

**Issue by xgarnaud** [tucanos/tucanos#16]
This is because the topological info in the remesher is defined at the vertices.
A way to avoid this would be, right after initialization of the remesher, to
 - detect the internal faces incorrectly tagged on a boundary
 - build the cavity for these face
 - fill these cavities with a vertex located at the face center

**Comment by jeromerobert** [comment]
How to:
* Add an item in the `CavityType` enum
* Add a `compute_cavity_face` in `remesher.rs` (for example same as `compute_cavity_edge` but with 3 intersections)
* Use `FilledCavity::from_cavity_and_new_vertex`
* In Remesher::new replace the `assert_eq` related to this bug
* Use `SimplexMesh::faces()` and `SimplexMesh::ftags()` to find the elements to split

**Comment by xgarnaud** [comment]
There is a similar issue when all the vertices of a face belong to edges with the same tag or when all the vertices of an edge have the same vertex tag. This can be fixed with edge splits.
